# Generated by Django 4.0.7 on 2023-03-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='friendship',
            field=models.CharField(choices=[('connected', 'Connected'), ('not_connected', 'Not Connected'), ('pending', 'Pending')], default='not_connected', max_length=20),
        ),
    ]
